# Generated by Django 5.2.6 on 2026-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('semester', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['department', 'semester', 'name'],
                'unique_together': {('name', 'department', 'semester')},
            },
        ),
    ]
